"""empty message

Revision ID: 96aac4f1b06a
Revises: a9e527bf3d4e
Create Date: 2025-07-31 17:47:33.438950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96aac4f1b06a'
down_revision = 'a9e527bf3d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('link', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('link')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
